# General Settings
set -g set-clipboard on
set -g mouse on
set -g allow-passthrough on
set -g focus-events on

set -s extended-keys always
set -s extended-keys-format csi-u

# Force tmux to recognize Kitty's extended keyboard capabilities
set -as terminal-features 'xterm-kitty:extkeys'

# Core Terminal & Colors (tmux-256color is recommended over xterm-256color inside tmux)
set -g default-terminal "tmux-256color"

# Handle dynamic cursor blinking (Cc)
set-option -as terminal-overrides ",xterm-kitty:Cc=\E]12;%p1%s\007"
set-option -as terminal-overrides ",xterm-256color:Cc=\E]12;%p1%s\007"

# Set status bar at top
set-option -g status-position top
